name: Deployment Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  checks: write
  actions: read

jobs:
  commit-cycle:
    runs-on: ubuntu-latest
    environment: regular-environment

    steps:
      - name: commit-cycle
        run: echo "commit cycle completed"

  acceptance-cycle:
    needs: [commit-cycle]
    runs-on: ubuntu-latest
    environment: regular-environment

    steps:
      - name: acceptance-cycle
        run: echo "acceptance cycle completed"

  deployment-cycle:
    needs: [commit-cycle, acceptance-cycle]
    runs-on: ubuntu-latest
    environment: regular-environment

    steps:
      - name: deployment-cycle
        run: echo "deployment completed"

  promote-beta-to-production:
    needs: [deployment-cycle]
    runs-on: ubuntu-latest
    environment: android-production
    
    steps:
        - name: promote-beta-to-production
          run: echo "promoted beta to production"